FROM jboss/wildfly
ADD showcase.war /opt/jboss/wildfly/standalone/deployments/
#RUN rm -rf /opt/jboss/wildfly/standalone/deployments/*
#ADD showcase.war /opt/jboss/wildfly/standalone/deployments/ROOT.war